name: "Discord Bot"
version: "1.0.0"
slug: "discord_bot"
description: "Runs Craig’s Discord bot in the background"
url: "https://github.com/cttautomations/ha-discord-bot-addon"
startup: application
boot: auto
init: false
host_network: true
options:
  discord_token: ""
schema:
  discord_token: str
