name: "Discord Bot"
version: "1.0.0"
slug: "discord_bot"
description: "Runs Craig’s Discord bot in the background"
startup: services
boot: auto
host_network: true
options:
  discord_token: "MTM1NjA1Njk4MjM2NDIyNTczMQ.GFnwLZ.DO6XewFprv4d9vSR3E0uZXiRwlqaRB0PfORYUw"
schema:
  discord_token: str
